apiVersion: apps/v1
kind: Deployment
metadata:
  name: nasa-apod-github-readme
  namespace: nasa-apod-github-readme
  labels:
    app: nasa-apod-github-readme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nasa-apod-github-readme
  template:
    metadata:
      labels:
        app: nasa-apod-github-readme
    spec:
      containers:
      - name: nasa-apod-github-readme
        image: ghcr.io/onlivio/nasa-apod-github-readme:v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: NASA_API_KEY
          valueFrom:
            secretKeyRef:
              name: nasa-api-key
              key: apiKey
      imagePullSecrets:
      - name: onlivio-ghcr
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nasa-api-key
  namespace: nasa-apod-github-readme
spec:
  encryptedData:
    apiKey: AgBBkHRGXQUInx+bgzpJ9sAIuA02FeRpEmNCfLqI1C0Z6+xnJKk9L0SH6cImw6VoaV+R0UBgp6nsCozng4uIhlJZPBxUlI/HFbvHfot6EZomkUH4Jh8tGf/w6m1VfPrMsxdRgXuqmRIHihw8i80GgDAR07XoCWk8JeSdDRUNr6XgK/xO9jFP0+sJHM6pPSutMuXuMYsKRQU8nKMrGGxCSZASlEMndgaXlywxt9nVb4qOzdgnhOGE+NV9aVBoLbOBxwCvyyC1D8A4FETnEmwLa20FhINF1SMZBg59eClZMfaYxL1E59g+T0fJu0dD0Xmh/m+a4k878sj/uCwRmcA0mJ4RlDK5KGetDTNivaF6MkDJZvDC5PrYdy+x0AW+ZGF5S8sPzTkKF4AEdwTIRF2wEugJP4wzWqKgY8DQdmDSKsWu4nGyBlMhCk1zcc2mH3KHllBioW87BeHvGSUMTpYBhbaWtrhezBQRb1x9w389plTZz7Y8wqEv6KfJnu49reOLjTHjtmcH2u1sBhtjDUUxaexpn+L2Y8bMDsf8PaQgH1l8B4CN84JpJSoYxkE2mmJ85cwVuMyAGdDCTy2syzXT8A9rfc+NO+o2VpyXlWGWyrLQeGVpx/oHRWFXW10x9ZAR7Ol+V0EUDn62VjRdPHLa+pXQAaQ7gnHVUEr4ud233iTPDV6+hBcGFgMYR7vev1a5aqFtWBSJ40Dp8DrDg8qBEOKnILwI4a+HYIcbkk1a6vnn4bqisAN6NWeA
  template:
    metadata:
      name: nasa-api-key
      namespace: nasa-apod-github-readme
